- name: Install git
  apt:
    name: git
    state: present

- name: Install Docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    - lsb-release

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

- name: Install Docker & Docker Compose
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Ensure Docker is running
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to Docker group
  user:
    name: "{{ vps_admin_user }}"
    groups: docker
    append: yes

- name: Inform user to re-login for Docker group
  debug:
    msg: "User {{ ansible_env.USER }} must log out and log back in, or run 'newgrp docker', for Docker group changes to take effect."
- name: Test Docker hello-world
  # Check and run the hello-world container only if the image isn't present
- name: Check for hello-world image
  command: docker image inspect hello-world
  register: hello_image_check
  failed_when: false
  changed_when: false

- name: Run docker hello-world if image missing
  command: docker run --rm hello-world
  become: yes
  when: hello_image_check.rc != 0
